name: Publish Zarf Skeleton

on:
  push:
    tags:
      - "*"

jobs:
  zarf:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main

    - name: Publish Zarf Package Skeleton
      run: zarf package publish . oci://ghcr.io/defenseunicorns/packages/leapfrogai